### ISSUE TITLE
Linebreaks in qrcode

### ISSUE THREAD

**Issue by eisenherzz** [cworreschk/grav-plugin-qrcode#6]
It is more a feature request.
I initially wanted to use your plug-in for generating my qrcode vcard (at the moment I use a command line tool to generate a png).
```
[qrcode]
BEGIN:VCARD
VERSION:4.0
N:Mustermann;Erika;;Dr.;
FN:Dr. Erika Mustermann
ORG:Wikimedia
ROLE:Kommunikation
TITLE:Redaktion & Gestaltung
PHOTO;MEDIATYPE=image/jpeg:http://commons.wikimedia.org/wiki/File:Erika_Mustermann_2010.jpg
TEL;TYPE=work,voice;VALUE=uri:tel:+49-221-9999123
TEL;TYPE=home,voice;VALUE=uri:tel:+49-221-1234567
ADR;TYPE=home;LABEL="Heidestraße 17\n51147 Köln\nDeutschland"
 :;;Heidestraße 17;Köln;;51147;Germany
EMAIL:erika@mustermann.de
REV:20140301T221110Z
END:VCARD
[/qrcode]
```
Unfortunately it seems that line breaks are not supported (yet). Or maybe I am missing something.

**Comment by cworreschk** [comment]
Hi @eisenherzz , line breaks are now supported in Version `1.1.0`. Thank you, for your request.

**Comment by eisenherzz** [comment]
Hi @cworreschk,

great work. I am now able to render my vCard with your plugin. Many
thanks and keep up the good work.
